-- ForkCart Default Pages Seed
-- Run on fresh installation to create starter pages (all as draft).
-- Idempotent: skips pages whose slug already exists.

INSERT INTO pages (title, slug, status, is_homepage, sort_order, seo_title, seo_description, content)
SELECT 'Homepage', 'homepage', 'draft', true, 0,
       'Welcome to Our Store',
       'Discover amazing products curated just for you. Free shipping, secure payments, and 24/7 support.',
       '{"ROOT":{"type":{"resolvedName":"Container"},"isCanvas":true,"props":{"paddingX":0,"paddingY":0,"maxWidth":"full","backgroundColor":"transparent"},"nodes":["hero1","iconGrid1","catGrid1","prodGrid1","testimonials1","newsletter1"],"displayName":"Container"},"hero1":{"type":{"resolvedName":"Hero"},"props":{"title":"Welcome to Our Store","subtitle":"Discover amazing products curated just for you","ctaText":"Shop Now","ctaLink":"/products","backgroundColor":"#1f2937","overlayOpacity":40,"height":"lg","alignment":"center","textColor":"#ffffff"},"nodes":[],"parent":"ROOT","displayName":"Hero Banner"},"iconGrid1":{"type":{"resolvedName":"IconGrid"},"props":{"items":[{"icon":"🚚","title":"Free Shipping","description":"On orders over $50"},{"icon":"🔒","title":"Secure Payment","description":"100% secure checkout"},{"icon":"↩️","title":"Easy Returns","description":"30-day return policy"},{"icon":"💬","title":"24/7 Support","description":"We are here to help"}],"columns":4,"iconSize":"md","alignment":"center"},"nodes":[],"parent":"ROOT","displayName":"Icon Grid"},"catGrid1":{"type":{"resolvedName":"CategoryGrid"},"props":{"columns":3},"nodes":[],"parent":"ROOT","displayName":"Category Grid"},"prodGrid1":{"type":{"resolvedName":"ProductGrid"},"props":{"limit":8,"sortBy":"createdAt","columns":4},"nodes":[],"parent":"ROOT","displayName":"Product Grid"},"testimonials1":{"type":{"resolvedName":"Testimonials"},"props":{"items":[{"name":"Sarah Johnson","role":"Verified Buyer","content":"Amazing quality! The product exceeded my expectations.","rating":5},{"name":"Mike Chen","role":"Repeat Customer","content":"Fast shipping and great customer service. Highly recommended!","rating":5},{"name":"Emma Davis","role":"Verified Buyer","content":"Love the attention to detail. Beautiful packaging and top-notch quality.","rating":4}],"columns":3,"showRating":true,"backgroundColor":"#f9fafb"},"nodes":[],"parent":"ROOT","displayName":"Testimonials"},"newsletter1":{"type":{"resolvedName":"Newsletter"},"props":{},"nodes":[],"parent":"ROOT","displayName":"Newsletter"}}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM pages WHERE slug = 'homepage');

INSERT INTO pages (title, slug, status, is_homepage, sort_order, seo_title, seo_description, content)
SELECT 'About Us', 'about-us', 'draft', false, 10,
       'About Us — Our Story',
       'Learn about our mission, values, and the team behind the brand.',
       '{"ROOT":{"type":{"resolvedName":"Container"},"isCanvas":true,"props":{"paddingX":0,"paddingY":0,"maxWidth":"full","backgroundColor":"transparent"},"nodes":["hero1","text1","divider1","text2","button1"],"displayName":"Container"},"hero1":{"type":{"resolvedName":"Hero"},"props":{"title":"About Us","subtitle":"Our story, our mission, our values","ctaText":"","backgroundColor":"#374151","height":"md","alignment":"center","textColor":"#ffffff"},"nodes":[],"parent":"ROOT","displayName":"Hero Banner"},"text1":{"type":{"resolvedName":"TextBlock"},"props":{"content":"We started with a simple idea: bring high-quality products directly to you. Since our founding, we have been committed to excellence in everything we do — from sourcing the finest materials to providing outstanding customer service.\n\nOur team is passionate about creating products that make a difference in your daily life. Every item in our store has been carefully selected to meet our high standards of quality and value.","fontSize":"base","alignment":"center","maxWidth":"md"},"nodes":[],"parent":"ROOT","displayName":"Text"},"divider1":{"type":{"resolvedName":"Divider"},"props":{"style":"solid","color":"#e5e7eb","thickness":1,"width":"1/4","marginY":32},"nodes":[],"parent":"ROOT","displayName":"Divider"},"text2":{"type":{"resolvedName":"TextBlock"},"props":{"content":"**Our Mission**\n\nTo provide our customers with the best products at fair prices, delivered with exceptional service. We believe that everyone deserves access to quality goods without compromise.","fontSize":"base","alignment":"center","maxWidth":"md"},"nodes":[],"parent":"ROOT","displayName":"Text"},"button1":{"type":{"resolvedName":"ButtonBlock"},"props":{"text":"Browse Our Products","link":"/products","variant":"primary","alignment":"center"},"nodes":[],"parent":"ROOT","displayName":"Button"}}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM pages WHERE slug = 'about-us');

INSERT INTO pages (title, slug, status, is_homepage, sort_order, seo_title, seo_description, content)
SELECT 'Contact', 'contact', 'draft', false, 20,
       'Contact Us',
       'Have a question? Get in touch with our team. We would love to hear from you.',
       '{"ROOT":{"type":{"resolvedName":"Container"},"isCanvas":true,"props":{"paddingX":0,"paddingY":0,"maxWidth":"full","backgroundColor":"transparent"},"nodes":["heading1","text1","form1","map1"],"displayName":"Container"},"heading1":{"type":{"resolvedName":"Heading"},"props":{"text":"Contact Us","level":"h1","alignment":"center"},"nodes":[],"parent":"ROOT","displayName":"Heading"},"text1":{"type":{"resolvedName":"TextBlock"},"props":{"content":"Have a question or feedback? We would love to hear from you. Fill out the form below and we will get back to you as soon as possible.","fontSize":"base","alignment":"center","maxWidth":"md"},"nodes":[],"parent":"ROOT","displayName":"Text"},"form1":{"type":{"resolvedName":"ContactForm"},"props":{"title":"","subtitle":"","buttonText":"Send Message","showPhone":true,"showSubject":true},"nodes":[],"parent":"ROOT","displayName":"Contact Form"},"map1":{"type":{"resolvedName":"MapEmbed"},"props":{"query":"New York, NY","height":350,"borderRadius":12},"nodes":[],"parent":"ROOT","displayName":"Map"}}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM pages WHERE slug = 'contact');

INSERT INTO pages (title, slug, status, is_homepage, sort_order, seo_title, seo_description, content)
SELECT 'Privacy Policy', 'privacy-policy', 'draft', false, 30,
       'Privacy Policy',
       'Read our privacy policy to understand how we collect, use, and protect your personal data.',
       '{"ROOT":{"type":{"resolvedName":"Container"},"isCanvas":true,"props":{"paddingX":0,"paddingY":0,"maxWidth":"full","backgroundColor":"transparent"},"nodes":["heading1","text1"],"displayName":"Container"},"heading1":{"type":{"resolvedName":"Heading"},"props":{"text":"Privacy Policy","level":"h1","alignment":"center"},"nodes":[],"parent":"ROOT","displayName":"Heading"},"text1":{"type":{"resolvedName":"TextBlock"},"props":{"content":"**Last updated: [Date]**\n\nThis Privacy Policy describes how [Your Company Name] (\"we\", \"us\", or \"our\") collects, uses, and shares your personal information when you visit our website or make a purchase.\n\n## Information We Collect\n\nWhen you visit our site, we automatically collect certain information about your device, including your web browser, IP address, time zone, and some of the cookies installed on your device.\n\nWhen you make a purchase or attempt to make a purchase, we collect your name, billing address, shipping address, payment information, email address, and phone number.\n\n## How We Use Your Information\n\nWe use the information we collect to:\n- Fulfill orders placed through the site\n- Communicate with you about orders, products, and promotions\n- Screen orders for potential risk or fraud\n- Improve and optimize our site\n\n## Sharing Your Information\n\nWe share your personal information with third parties to help us use your information as described above. For example, we use payment processors to process your payment securely.\n\n## Your Rights\n\nYou have the right to access, correct, or delete any personal information we have collected about you. Please contact us at [email] to exercise these rights.\n\n## Contact Us\n\nFor more information about our privacy practices, please contact us at [email].","fontSize":"base","alignment":"left","maxWidth":"md"},"nodes":[],"parent":"ROOT","displayName":"Text"}}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM pages WHERE slug = 'privacy-policy');

INSERT INTO pages (title, slug, status, is_homepage, sort_order, seo_title, seo_description, content)
SELECT 'Terms of Service', 'terms-of-service', 'draft', false, 40,
       'Terms of Service',
       'Read our terms of service for the rules and regulations governing use of our online store.',
       '{"ROOT":{"type":{"resolvedName":"Container"},"isCanvas":true,"props":{"paddingX":0,"paddingY":0,"maxWidth":"full","backgroundColor":"transparent"},"nodes":["heading1","text1"],"displayName":"Container"},"heading1":{"type":{"resolvedName":"Heading"},"props":{"text":"Terms of Service","level":"h1","alignment":"center"},"nodes":[],"parent":"ROOT","displayName":"Heading"},"text1":{"type":{"resolvedName":"TextBlock"},"props":{"content":"**Last updated: [Date]**\n\nPlease read these Terms of Service (\"Terms\") carefully before using our website operated by [Your Company Name].\n\n## 1. Agreement to Terms\n\nBy accessing or using our service, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.\n\n## 2. Purchases\n\nIf you wish to purchase any product made available through the service, you may be asked to supply certain information relevant to your purchase including your credit card number, expiration date, billing address, and shipping information.\n\n## 3. Products & Availability\n\nWe reserve the right to limit the quantities of any products or services that we offer. All descriptions of products or pricing are subject to change at any time without notice.\n\n## 4. Returns & Refunds\n\nOur return and refund policy is outlined separately on our Returns page. Products can generally be returned within 30 days of receipt.\n\n## 5. Intellectual Property\n\nThe service and its original content, features, and functionality are owned by [Your Company Name] and are protected by international copyright, trademark, and other intellectual property laws.\n\n## 6. Limitation of Liability\n\nIn no event shall [Your Company Name] be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service.\n\n## 7. Changes\n\nWe reserve the right to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.\n\n## 8. Contact Us\n\nIf you have any questions about these Terms, please contact us at [email].","fontSize":"base","alignment":"left","maxWidth":"md"},"nodes":[],"parent":"ROOT","displayName":"Text"}}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM pages WHERE slug = 'terms-of-service');
