import type { AIProviderRegistry, ChatMessage } from '@forkcart/ai';
import { createLogger } from '../lib/logger';

const logger = createLogger('product-ai-service');

/** Dependencies for the ProductAIService */
export interface ProductAIServiceDeps {
  aiRegistry: AIProviderRegistry;
}

/** Minimal product data needed for AI generation */
export interface ProductAIInput {
  name: string;
  description?: string | null;
  shortDescription?: string | null;
  sku?: string | null;
  price: number; // in cents
  currency: string;
  categoryNames?: string[];
  attributes?: Record<string, string>;
}

/** SEO metadata generated by AI */
export interface SEOMetadata {
  title: string;
  description: string;
  keywords: string[];
}

/** Bullet points generated by AI */
export interface BulletPoints {
  points: string[];
}

const SYSTEM_PROMPT =
  'Du bist ein E-Commerce Copywriter. Schreibe überzeugende, SEO-optimierte Produktbeschreibungen auf Deutsch. ' +
  'Schreibe in einem professionellen aber nahbaren Ton. ' +
  'Formatiere den Text als HTML mit <p>-Tags für Absätze. Verwende KEIN Markdown.';

/**
 * AI service for generating product content.
 * Uses the configured AI provider from the registry.
 */
export class ProductAIService {
  private readonly registry: AIProviderRegistry;

  constructor(deps: ProductAIServiceDeps) {
    this.registry = deps.aiRegistry;
  }

  /** Generate a product description from name, category, and attributes */
  async generateDescription(product: ProductAIInput): Promise<string> {
    const provider = this.getProvider();
    const priceFormatted = `${(product.price / 100).toFixed(2)} ${product.currency}`;

    let prompt = `Schreibe eine ansprechende Produktbeschreibung für: "${product.name}"`;
    prompt += `\nPreis: ${priceFormatted}`;
    if (product.categoryNames?.length) {
      prompt += `\nKategorie: ${product.categoryNames.join(' > ')}`;
    }
    if (product.attributes && Object.keys(product.attributes).length > 0) {
      prompt += '\nEigenschaften:';
      for (const [key, value] of Object.entries(product.attributes)) {
        prompt += `\n- ${key}: ${value}`;
      }
    }
    if (product.shortDescription) {
      prompt += `\nKurzbeschreibung: ${product.shortDescription}`;
    }
    prompt += '\n\nSchreibe 2-3 Absätze. Formatiere als HTML mit <p>-Tags.';

    const messages: ChatMessage[] = [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: prompt },
    ];

    logger.info({ productName: product.name }, 'Generating product description');
    const response = await provider.chat(messages, { maxTokens: 800, temperature: 0.8 });
    return response.content;
  }

  /** Generate SEO metadata (title, description, keywords) */
  async generateSEOMetadata(product: ProductAIInput): Promise<SEOMetadata> {
    const provider = this.getProvider();

    const prompt =
      `Generiere SEO-Metadaten für das Produkt "${product.name}".` +
      (product.description ? `\nBeschreibung: ${product.description.slice(0, 500)}` : '') +
      '\n\nAntworte NUR mit JSON in diesem Format (keine Erklärung):' +
      '\n{"title": "max 60 Zeichen", "description": "max 155 Zeichen", "keywords": ["keyword1", "keyword2", ...]}';

    const messages: ChatMessage[] = [
      {
        role: 'system',
        content:
          'Du bist ein SEO-Spezialist für E-Commerce. Antworte ausschließlich mit validem JSON.',
      },
      { role: 'user', content: prompt },
    ];

    logger.info({ productName: product.name }, 'Generating SEO metadata');
    const response = await provider.chat(messages, { maxTokens: 300, temperature: 0.5 });

    try {
      // Strip markdown code fences if present
      const cleaned = response.content.replace(/```json?\s*/g, '').replace(/```\s*/g, '');
      const parsed = JSON.parse(cleaned) as SEOMetadata;
      return {
        title: String(parsed.title ?? product.name).slice(0, 60),
        description: String(parsed.description ?? '').slice(0, 155),
        keywords: Array.isArray(parsed.keywords) ? parsed.keywords.map(String).slice(0, 10) : [],
      };
    } catch {
      logger.warn('Failed to parse SEO metadata JSON, returning defaults');
      return {
        title: product.name.slice(0, 60),
        description: (product.shortDescription ?? product.name).slice(0, 155),
        keywords: [],
      };
    }
  }

  /** Generate 3-5 selling point bullet points */
  async generateBulletPoints(product: ProductAIInput): Promise<BulletPoints> {
    const provider = this.getProvider();

    const prompt =
      `Erstelle 3-5 überzeugende Selling Points (Bullet Points) für: "${product.name}"` +
      (product.description ? `\nBeschreibung: ${product.description.slice(0, 500)}` : '') +
      '\n\nAntworte NUR mit JSON: {"points": ["Punkt 1", "Punkt 2", ...]}';

    const messages: ChatMessage[] = [
      {
        role: 'system',
        content:
          'Du bist ein E-Commerce Copywriter. Schreibe kurze, prägnante Selling Points. Antworte nur mit JSON.',
      },
      { role: 'user', content: prompt },
    ];

    logger.info({ productName: product.name }, 'Generating bullet points');
    const response = await provider.chat(messages, { maxTokens: 300, temperature: 0.7 });

    try {
      const cleaned = response.content.replace(/```json?\s*/g, '').replace(/```\s*/g, '');
      const parsed = JSON.parse(cleaned) as BulletPoints;
      return {
        points: Array.isArray(parsed.points) ? parsed.points.map(String).slice(0, 5) : [],
      };
    } catch {
      logger.warn('Failed to parse bullet points JSON');
      return { points: [] };
    }
  }

  /** Improve an existing product description */
  async improveDescription(product: ProductAIInput, currentDescription: string): Promise<string> {
    const provider = this.getProvider();

    const prompt =
      `Verbessere die folgende Produktbeschreibung für "${product.name}":` +
      `\n\n${currentDescription}` +
      '\n\nMach den Text überzeugender, SEO-optimierter und besser lesbar.' +
      ' Behalte die Kernaussagen bei. Formatiere als HTML mit <p>-Tags.';

    const messages: ChatMessage[] = [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: prompt },
    ];

    logger.info({ productName: product.name }, 'Improving product description');
    const response = await provider.chat(messages, { maxTokens: 800, temperature: 0.7 });
    return response.content;
  }

  /** Get the configured provider or throw */
  private getProvider() {
    const provider = this.registry.getConfiguredProvider();
    if (!provider) {
      throw new Error('No AI provider configured. Configure one in Settings → AI.');
    }
    return provider;
  }
}
